GET http://localhost:3000/api/libros

###
GET http://localhost:3000/api/libros/6242c4d343de650304df4c9a

###
GET http://localhost:3000/api/categorias

###
GET http://localhost:3000/api/categorias?limit=2&offset=0

###
GET http://localhost:3000/api/categorias/6242c38a8de0ff314ecca275

###
PATCH http://localhost:3000/api/libros/62431456b6e01995416169a4
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImRhbmltb3Jlbm85NCIsImV4cCI6MTY1MzAzMjc0NTg0MH0.1q00ntmQ6FGd-DjLcji0DA-xGFrXRAGgCIEFTvTEX9c
Content-Type: application/json

{
    "precio": 9.80
}
    

###
DELETE http://localhost:3000/api/libros/62431456b6e01995416169a4
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImRhbmltb3Jlbm85NCIsImV4cCI6MTY1MzAzMjc0NTg0MH0.1q00ntmQ6FGd-DjLcji0DA-xGFrXRAGgCIEFTvTEX9c

###
POST http://localhost:3000/api/libros
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImRhbmltb3Jlbm85NCIsImV4cCI6MTY1MzAzMjc0NTg0MH0.1q00ntmQ6FGd-DjLcji0DA-xGFrXRAGgCIEFTvTEX9c
Content-Type: application/json

{
    "titulo": "Casi una novela 7",
    "precio": 6.60,
    "autor": "62096ca0008515ef865e17b0",
    "categoria": "6242c2cc8de0ff314ecca274"
}

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "nombre": "Tamara Pérez",
    "username": "tamiperez90",
    "email": "tamiperez_90@hotmail.com",
    "password": "123456"
}

###
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "username": "danimoreno94",
    "password": "123456"
}

###
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "username": "tamiperez90",
    "password": "123456"
}

###
GET http://localhost:3000/api/users/danimoreno94

###
POST http://localhost:3000/api/compras
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InRhbWlwZXJlejkwIiwiZXhwIjoxNjUzMzM1MjA1NjAzfQ.jDxToLpzfvrvQpdc1cCCJPsKgNIIVfbWIW7YZLuGM_4
Content-Type: application/json

{
    "vendedor": "627e0c6ea5b4f89db9f0cac9",
    "comprador": "627e0c45a5b4f89db9f0cac5",
    "libro": "6242c55e43de650304df4ca6",
    "valoracion": 5
}
